[package]
name = "actix-web-public-path"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-utils = "3.0.0"
actix-web = "4.0.1"
derive_more = "0.99.17"
serde = "1.0.136"
